version: "3.8"

services:
  db:
    image: postgres:13.5-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipes

  web:
    image: python:3.9-slim
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

volumes:
  db-data: